---
title: "ADS fundamentals"
---

Welcome to the course "Fundamental Techniques in Data Science with R".

## Important links

-   Coordinator: [Dr L. Boeschoten](https://www.uu.nl/medewerkers/LBoeschoten)

-   Lecturer: [Dr K.M. Lang](https://www.uu.nl/staff/KMLang)

-   Instructors: [Dr A. Giachanou](https://www.uu.nl/medewerkers/AGiachanou) and [T.C. Carrière, MSc](https://www.uu.nl/medewerkers/TCCarriere)

-   Rooms: See [MyTimetable](https://mytimetable.uu.nl/schedule)

-   [Course manual](manual.qmd)

-   [Instructions group assignments](assignments.qmd)

-   [Link to upload group assignments](https://surfdrive.surf.nl/index.php/s/vDu5h9LNlwE6KhN)

-   [Exam information](exam.qmd)

## Weekly schedule

+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| # Week | # Date      | # Content                    | # Prepare                                                                                                                                       |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 1      | 10-11 (Mon) | [Lecture](lectures.qmd#w1)   | -   Read [course manual](manual.qmd)                                                                                                            |
|        |             |                              | -   Check [preparation](preparation.qmd)                                                                                                        |
|        |             |                              | -   Read [R4DS](https://r4ds.hadley.nz/) Ch. 3, 4, 7, 13, 16                                                                                    |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 1      | 11-11 (Tue) | Q&A - online                 |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 1      | 13-11 (Thu) | WG                           | Be present to pass the course!!                                                                                                                 |
|        |             |                              |                                                                                                                                                 |
|        |             |                              | -   [Slides](workgroups/WG1.qmd)                                                                                                                |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 2      | 17-11 (Mon) | Deadline lab 1: 15:00        | -   [Lab 1](labs/lab1.qmd) ([solutions](labs/lab1_answers.qmd))                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 2      | 17-11 (Mon) | [Lecture](lectures.qmd#w2)   | -   Read [R4DS](https://r4ds.hadley.nz/) Ch. 1, 9, 10                                                                                           |
|        |             |                              | -   Read [SDAM](https://mspeekenbrink.github.io/sdam-book/index.html) Ch. 4                                                                     |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 2      | 18-11 (Tue) | Q&A - online                 |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 2      | 20-11 (Thu) | WG                           |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 3      | 24-11 (Mon) | Deadline lab 2: 15:00        | -   [Lab 2](labs/lab2.qmd) ([solutions](labs/lab2_answers.qmd))                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 3      | 24-11 (Mon) | [Lecture](lectures.qmd#w3)   | -   Read [SDAM](https://mspeekenbrink.github.io/sdam-book/index.html) Ch. 5.1 - 5.6, 6.1                                                        |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 3      | 25-11 (Tue) | Q&A - online                 |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 3      | 27-11 (Thu) | WG                           |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 4      | 1-12 (Mon)  | Deadline lab 3: 15:00        | -   [Lab 3](labs/lab3.qmd) ([solutions](/labs/lab3_answers.qmd))                                                                                |
|        |             |                              | -   [demo](labs/demo4.html)                                                                                                                     |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 4      | 1-12 (Mon)  | [Lecture](lectures.qmd#w4)   | -   Read [SDAM](https://mspeekenbrink.github.io/sdam-book/index.html) Ch. 5.7 - 5.9                                                             |
|        |             |                              | -   Read [this](https://stats.oarc.ucla.edu/r/dae/robust-regression/) and [this](https://sandwich.r-forge.r-project.org/articles/sandwich.html) |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 4      | 2-12 (Tue)  | Q&A - online                 |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 4      | 4-12 (Thu)  | WG                           |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 5      | 8-12 (Mon)  | Deadline lab 4: 15:00        | -   [Lab 4](labs/lab4.qmd) ([solutions](/labs/lab4_answers.qmd))                                                                                |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 5      | 8-12 (Mon)  | Deadline assignment 1: 15:00 |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 5      | 8-12 (Mon)  | [Lecture](lectures.qmd#w5)   | -   Read [SDAM](https://mspeekenbrink.github.io/sdam-book/index.html) Ch. 12.1 - 12.5, 12.8                                                     |
|        |             |                              | -   Read [this](https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/)              |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 5      | 9-12 (Tue)  | Q&A - online                 |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 5      | 11-12 (Thu) | WG                           |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 6      | 15-12 (Mon) | Deadline lab 5: 15:00        | -   [Lab 5](labs/lab5.qmd) ([solutions](/labs/lab5_answers.qmd))                                                                                |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 6      | 15-12 (Mon) | [Lecture](lectures.qmd#w6)   | -   Read [this](https://stats.oarc.ucla.edu/r/dae/logit-regression/)                                                                            |
|        |             |                              | -   Read [Book420](https://book.stat420.org/) CH. 17.4                                                                                          |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 6      | 16-12 (Tue) | Q&A - online                 |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 6      | 18-12 (Thu) | WG                           |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 7      | 12-1 (Mon)  | Deadline lab 6: 15:00        | -   [Lab 6](labs/lab6.qmd) ([solutions](/labs/lab6_answers.qmd))                                                                                |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 7      | 12-1 (Mon)  | [Recap](lectures.qmd#w7)     |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 7      | 15-1 (Thu)  | Presentations assignment 2   | Be present from 09:00 to 12:45 to pass the course!!                                                                                             |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| 8      | 22-1 (Thu)  | Exam                         |                                                                                                                                                 |
+--------+-------------+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
