---
title: "Lectures"
toc: false
---

Below, you can access the lecture slides and associated materials for each week.

## Week 1 {#w1}

R Programming Fundamentals

- [Lecture Slides](lectures/l1/lecture1.pdf)
- [Project Organization Demo](assets/project_organization.zip)
   - This link will download a ZIP archive that you must unpack on your computer.

## Week 2 {#w2}

Data Visualization & Simple Linear Regression

- [Visualization Lecture Slides](lectures/l2/visualization.pdf)
- [SLR Lecture Slides](lectures/l2/slr.pdf)

## Week 3 {#w3}

Multiple Linear Regression

- [Lecture Slides](lectures/l3/mlr.pdf)

## Week 4 {#w4}

MLR Assumptions & Diagnostics

- [Assumptions Lecture Slides](lectures/l4/assumptions.pdf)
- [Influential Observations Lecture Slides](lectures/l4/influence.pdf)

## Week 5 {#w5}

Generalized Linear Models & Logistic Regression

- [GLM & Logistic Regression Lecture Slides](lectures/l5/glm.pdf)
- [Extra: Extended Example Slides](lectures/l5/extra.pdf)

## Week 6

Logistic Regression Assumptions & Assessing Classification Performance

- [Assumption \& Diagnostics Slides](lectures/l6/log_reg_diagnostics.pdf)
- [Classification Performance Slides](lectures/l6/log_reg_performance.pdf)

## Week 7

Wrap Up & Review
