---
title: "Course manual"
---

## Course content

Regression techniques are widely used to quantify the relationship between two or more variables. In data science, linear and logistic regression are common and powerful techniques for evaluating such relations. These techniques are only useful, however, once you understand when and how to apply them. In this course, students will learn how to apply linear and logistic regression with the R statistical software package.

This course will introduce students to the principles of analytical data science, linear and logistic regression, and the basics of statistical learning. Students will develop fundamental R programming skills and will gain experience with tidyverse: visualize data with ggplot2 and performing basic data wrangling with dplyr. This course helps prepare students for an entry-level research career (e.g. junior researcher or research assistant) or further education in research (e.g., a \[research\] Master program or a PhD).

## Course structure

In seven weeks, you will learn the basics of data handling and statistical programming with R and details about regression techniques in the context of statistical inference, prediction, and classification. Each week will comprise four activities:

-   During the weekly **in-person lectures**, we will cover the theoretical content.

-   During the weekly **in-person workgroup** meetings, you will work on real-world data analysis with a group of your peers.

-   Weekly **self-study practical exercises** connect the statistical theory to practice by applying the lecture content in the R statistical programming language.

-   There is an **online weekly Q&A** session in case you get stuck or have questions.

## How to pass the course

Your final grade consists of three elements:

| Grade component         | Weight | Required minimum grade |
|-------------------------|--------|------------------------|
| Group assignment 1      | 25%    | 5.5                    |
| Group assignment 2      | 25%    | 5.5                    |
| Written exam in Remindo | 50%    | 5.5                    |

### Attendance

During this course, you will attend 7 lectures, 7 workgroup sessions and hand in 6 practical assignments.

**Attendance** for the lectures and the workgroup sessions **is mandatory**. You work on your group assignments during the workgroup meetings. For a collaborative spirit, attendance is crucial.

### Testing procedure

There are two opportunities per year to take a test.

-   Should circumstances prevent you from taking the first opportunity, you will be invited to the second. It is not necessary to deregister.

-   If you do not obtain a satisfactory final grade on the second opportunity, you will have to retake the course in the 2026-2027 academic year. See detailed information on testing on [the student website](https://students.uu.nl/en/fss/clinical-child-and-adolescent-psychology/practical-information/academic-policies-and-procedures/testing).

-   but you have obtained a pass for one part (e.g. an assignment or the exam), then you do not have to redo this part next year.

## Course objectives and learning outcomes

### Course objectives

At the end of this course, students are able to:

1.  Identify key statistical concepts such as:

-   (Conditional) probability 

-   Inference 

-   Estimation 

-   Prediction 

-   Classification 

-   Sampling variability 

-   Statistical modeling 

-   Residuals Fitted values

2.  Choose an appropriate regression model for a given research scenario.

3.  Explain the differences/similarities between statistical inference and model-based prediction/classification; give examples of each type of problem.

4.  Identify the assumptions of linear and logistic regression; describe the consequences of violating these assumptions.

5.  Describe the three components of a generalized linear model and how these components are specified in logistic regression.

6.  Interpret the estimates from linear and logistic regression models, and use these estimates to answer research questions.

7.  Use the R statistical software platform to perform basic statistical programming, data manipulation, data visualization, and basic data wrangling.

8.  Use the R statistical software platform to perform, interpret, and evaluate linear and logistic regression analyses on real-world data.

9.  Interpret R output and use the results to answer research questions.

10. Use Quarto to document the results of a statistical analysis.

### Rationale for assessment strategy

In this course, skills and knowledge are evaluated with two types of assignment.

1.    The exam evaluates knowledge and understanding of statistical concepts (Learning goal 1), the ability to critically evaluate research problems and statistical methods (Learning goals 2–5), and the ability to interpret statistical results and software output and apply these interpretations (Learning goals 6 & 9). 

2.    The group assignments evaluate the student’s ability to work with data, solve basic data analytic problems, execute quantitative data analyses on real-world data sets, and document the results (learning goals 6–10).

## Important notice about the use of course material

The course material you receive in this course is intended for your personal learning process. All course content, including course manuals, presentations, recordings, (elaborations of) assignments and additional documents, is the intellectual property of Utrecht University. This material may not be shared, distributed or sold, both online and offline, without the express written permission of the university. NB: This also concerns entering course material in GenAI.

We would like to emphasize that taking this course is an investment in your own development. The material has been carefully put together to deepen your understanding of the field and strengthen your skills. By distributing or even selling this material, you violate the intellectual property of the UU. We therefore ask you to respect these guidelines and contribute to a fair and honest learning environment.

## Fraud, plagiarism and use of generative AI

Plagiarism and fraud are serious academic offenses. Plagiarism is defined as the use of another person’s work without proper acknowledgment. This includes copying and pasting text from the internet, from books, or from other students. If you use text from another source, you must put it in quotation marks and provide a citation. If you do not, you are committing plagiarism. Fraud is defined as the use of dishonest methods to gain an unfair advantage. This includes copying another student’s work, submitting work that is not your own, or submitting the same work for two different courses. If you commit fraud or plagiarism, you will fail the course. If you are not sure what constitutes plagiarism or fraud, please see the (UU Fraud and plagiarism policy)\[https://students.uu.nl/en/practical-information/policies-and-procedures/fraud-and-plagiarism\].

The use of generative AI (e.g., chatGPT) in the group assignments is allowed only for the following cases:

-   Gain inspiration

-   Ask for help on how to tackle an assignment

The use of generative AI must be clearly indicated in the assignment, clearly identifying the specific model used and for what purpose. The use of generative AI for other purposes is not allowed.
